# Description
# ===========
# This playbook create an Azure VM with public IP, and open 22 port for SSH

- name: Create Azure VM
  hosts: localhost
  connection: local
  vars:
    resource_group: vmcreate001
    vm_name: testvm
    location: westeurope
  tasks:
  - name: Create a resource group
    azure_rm_resourcegroup:
      name: "{{ resource_group }}"
      location: "{{ location }}"
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}"
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}"
      address_prefix: "10.0.1.0/24"
      virtual_network: "{{ vm_name }}"
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: "{{ resource_group }}"
      allocation_method: Static
      name: "{{ vm_name }}"
      domain_name_label: "{{ vm_name }}-00121"
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}"
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
        - name: HTTP
          protocol: Tcp
          destination_port_range: 80
          access: Allow
          priority: 1002
          direction: Inbound
  - name: Create virtual network inteface card
    azure_rm_networkinterface:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}"
      virtual_network: "{{ vm_name }}"
      subnet: "{{ vm_name }}"
      public_ip_name: "{{ vm_name }}"
      security_group: "{{ vm_name }}"
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}"
      vm_size: Standard_DS1_v2
      ssh_public_keys:
        - key_data: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCsk5MB07uAjqbvSXFhO2ohOPYpboZVMLIdSX9TxGmP9hwhh2LlUpYP+278U17YsrpYZVCgcBWSLLaAI4HOjeUraq3Yez8ZroHwM0dKaIjGOHOBSMisnWzPF0dKjQVp8ZhxLsU7LsZXaHWMfcp02gGod43w0SZVcDLiupnLZjf2eOB8h0PpdYerPDRqi4SDKrviUTcDZWJVnB1cNZtfPc/fXHHfG0OA2eXKdOyzivu/7ZMnfm6slMUjC/lr67p3OmNOHfgEYaQmMi3esV92/52V31PJ22ZoBINq/Ou2K2nLHqNk6WG837ajPfkYYrFR30BhZ29Rh+xx0FNnky87cNmt root@tower.example.com
          path: /home/azureuser/.ssh/authorized_keys
      admin_username: azureuser
      admin_password: Password@123
      network_interfaces: "{{ vm_name }}"
      
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7-CI'
        version: latest
